/*
* Automatically generated by 'ng g ng-alain:plugin icon'
* @see https://ng-alain.com/cli/plugin#icon
*/

import {
    FullscreenExitOutline,
    FullscreenOutline,
    ProfileOutline,
    SettingOutline,
    LogoutOutline,
    CloseOutline,
    CaretDownFill,
    PlusOutline,
    FilterOutline,
    UserOutline,
    LockOutline,
    QuestionCircleFill,
    WarningFill,
    SyncOutline,
    UpCircleFill,
    DownCircleFill,
    StopFill,
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
    FullscreenExitOutline,
    FullscreenOutline,
    ProfileOutline,
    SettingOutline,
    LogoutOutline,
    CloseOutline,
    CaretDownFill,
    PlusOutline,
    FilterOutline,
    UserOutline,
    LockOutline,
    QuestionCircleFill,
    WarningFill,
    SyncOutline,
    UpCircleFill,
    DownCircleFill,
    StopFill,
];
